name: react-native-android
on:
  push:
    branches:
    - master
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name'
        default: '1.0.0'
      versionCode:
        description: 'Version code'     
        required: true
        default: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  build-android:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install
      - name: Build
        run: ./android/gradlew bundleRelease
        env:
          ALTERGO_KEYSTORE_FILE: ${{ secrets.ALTERGO_KEYSTORE_FILE }}
          ALTERGO_KEYSTORE_PASSWORD: ${{ secrets.ALTERGO_KEYSTORE_PASSWORD }}
          ALTERGO_KEY_ALIAS: ${{ secrets.ALTERGO_KEY_ALIAS }}
          ALTERGO_KEY_PASSWORD: ${{ secrets.ALTERGO_KEY_PASSWORD }}
          VERSION_NAME: ${{ github.event.inputs.versionName }}
          VERSION_CODE: ${{ github.event.inputs.versionCode }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.bundle
          path: android/app/build/outputs/bundle/release/
