name: build-android

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: false
        default: '1.0.0'
      version_code:
        description: 'Version code'
        required: true
        default: '1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install

      - name: Lint
        run: yarn lint && npx conventional-changelog -p angular -i CHANGELOG.md -s && cat CHANGELOG.md

  build-android:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install

      - name: Build
        run: ./android/gradlew bundleRelease -p android
        env:
          ALTERGO_KEYSTORE_FILE: ${{ secrets.ALTERGO_KEYSTORE_FILE }}
          ALTERGO_KEYSTORE_PASSWORD: ${{ secrets.ALTERGO_KEYSTORE_PASSWORD }}
          ALTERGO_KEY_ALIAS: ${{ secrets.ALTERGO_KEY_ALIAS }}
          ALTERGO_KEY_PASSWORD: ${{ secrets.ALTERGO_KEY_PASSWORD }}
          VERSION_NAME: ${{ github.event.inputs.version_name }}
          VERSION_CODE: ${{ github.event.inputs.version_code }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.bundle
          path: android/app/build/outputs/bundle/release/
